### ISSUE TITLE
change into O(1)

### ISSUE THREAD

**Issue by ParkInHyeok** [AlchemicSH/sum_test#1]
https://github.com/AlchemicSH/sum_test/commit/0b1487879755cceb5277c9e117736041f2e0c8e9

**Comment by AlchemicSH** [comment]
Done in. https://github.com/AlchemicSH/sum_test/commit/8ea1cad13cb0764d92e96ddffcf28c1e89dc8ca6#diff-efbd37df70a1b632136638d16a403122
